name: RunnerV1

on:
  push:
    branches:
      - main
jobs:
  dagger:
    name: Run Dagger Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dagger Pipeline
        uses: dagger/dagger-for-github@v8.2.0
        with:
          module: .
          call: download -o ./model
          version: latest

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./model/artifacts/*.pkl

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
